### ISSUE TITLE
Remove import

### ISSUE THREAD

**Issue by kevinbird15** [fastaudio/fastai_audio#27]
https://github.com/mogwai/fastai_audio/blob/e8499b72876292b5013f2382a7eef7317aa674e8/audio/audio.py#L11

I want to discuss removing this line.  I have removed it in my local environment and added the audio folder into the fastai core library and it allows me to do `from fastai.audio import *`

Just want to discuss what the `from audio import *` is doing in the current library and see if there is another way to achieve the results.

**Comment by mogwai** [comment]
This is indeed a pain point for using the library currently. You could indeed move the audio folder into the fast ai library but of course we can't do that unless fastai merge our code into there. 

We've thought it might be a good idea to make a setup.py file so that you can install the library through pip, then you could just:

`from fastai_audio import *`

**Comment by mogwai** [comment]
In fact the specific line that your referencing could be removed

**Comment by kevinbird15** [comment]
I was thinking it could be removed.  I just wanted to make sure there was no unintended consequences to doing that.

**Comment by mogwai** [comment]
Yes it could be removed
